name: Run Tests

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Puppeteer libraries
        run: |
            sudo apt-get update
            sudo apt-get install -y libgbm1
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
