name: Run Tests

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install front end NPM deps
        run: npm ci
      - name: Install back end NPM deps
        run: cd backend && npm ci && cd ..
      - run: npm test
