name: Run Tests

on: [push]

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: ls
              run: ls -al
            - name: Install Dependencies
              run: npm install
            - name: Run Tests
              run: npm test